name: "main"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Run in dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/yongenaelf/aelfinity-workshop
          push: never
          runCmd: |
            cd src
            dotnet build
            cd ../test
            dotnet test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dll patched
          path: |
            **/*.patched